package com.jecminek.edventure_backend.enums

enum class Faculty {
    FACULTY_OF_AGRISCIENCES,
    FACULTY_OF_FORESTRY_AND_WOOD_TECHNOLOGY,
    FACULTY_OF_BUSINESS_AND_ECONOMICS,
    FACULTY_OF_HORTICULTURE,
    FACULTY_OF_REGIONAL_DEVELOPMENT_AND_INTERNATIONAL_STUDIES,
    INSTITUTE_OF_LIFELONG_LEARNING
}