INSERT INTO subject(id,code,name,faculty_id) VALUES (8,'AGRR','Agrobyznys v rozvoji regionů',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (9,'AESSL','Agroekosystémové služby',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (10,'AGCVZ','Agrochemie a výživa rostlin',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (11,'AGRT','Agroturistika',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (12,'AGRTSP','Agroturistika speciální',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (13,'AZE','Alternativní zdroje energie',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (14,'ANPG','Analýzy v prostředí GIS',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (15,'AFYR','Anatomie a fyziologie rostlin',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (16,'AFYZ','Anatomie a fyziologie zvířat',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (17,'AHIZ-VS','Anatomie a histologie zvířat MBB',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (18,'AHIZ','Anatomie a histologie zvířat ZOO',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (19,'AMOR','Anatomie a morfologie rostlin',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (20,'AVTZ','Aplikace výpočetní techniky v zemědělství',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (21,'AVTZ1','Aplikace výpočetní techniky v zemědělství ZI',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (22,'AGER','Aplikovaná genetika rostlin',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (23,'AGEZ','Aplikovaná genetika zvířat',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (24,'APMY','Aplikovaná mykologie',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (25,'ABIOT','Aplikované biotechnologie',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (26,'APSW','Aplikovaný pěstitelský software',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (27,'CBAN','Bioanalytické metody',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (28,'CBIN','Biochemie N',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (29,'BICRO','Biochemie rostlin',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (30,'CBIZ','Biochemie v TP',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (31,'CBIVYZ','Biochemie výživy',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (32,'BIOKL','Bioklimatologie',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (33,'BICHOR','Biologická a chemická ochrana rostlin',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (34,'BZRV','Biologické základy RV',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (35,'BZZV','Biologické základy ŽV',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (36,'BION','Bionika',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (37,'BIKPZ','Biotechnologie krmných a potravinových zdrojů',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (38,'BIVYCL','Biotechnologie ve výživě člověka',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (39,'BOT','Botanika',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (40,'BFYR','Botanika a fyziologie rostlin',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (41,'CUKTE','Cukrářské technologie',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (42,'DESM','Destinační management',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (43,'DMV','Diagnostika motorových vozidel',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (44,'DIPSE','Diplomový seminář',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (45,'DZKLIM','Dopady změny klimatu',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (46,'DMEP','Doprava a mobilní energetické prostředky',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (47,'DOIN','Dopravní inženýrství',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (48,'EKRI','Ekologická rizika',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (49,'ESCHZ','Ekologické systémy chovu zvířat',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (50,'EKZ','Ekologické zemědělství',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (51,'EKOL','Ekologie',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (52,'EKOL2','Ekologie II',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (53,'EVP','Ekologie vodního prostředí',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (54,'ESSL','Ekosystémové služby',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (55,'CTX','Ekotoxikologie',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (56,'ENVIR','Environmentalistika',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (57,'ENAU','Environmentální audit',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (58,'ENET','Environmentální etika',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (59,'ENPOL','Environmentální politika',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (60,'ETK','Etologie koní',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (61,'EXIN','Expertní inženýrství',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (62,'FAMNG','Facility management',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (63,'FCHZ','Farmové chovy zvěře',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (64,'FIPS','Finanční produkty a služby',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (65,'FRP','Finanční řízení podniku',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (66,'FRPAG','Finanční řízení podniku v agrobyznysu',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (67,'FYC','Fytocenologie',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (68,'FYPAT','Fytopatologie',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (69,'FYZ2','Fyzika II',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (70,'FVO','Fyzikální vlastnosti odpadů',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (71,'FYMIK','Fyziologie mikroorganismů',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (72,'FYR','Fyziologie rostlin',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (73,'FYR1','Fyziologie rostlin 1',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (74,'GBOCH','Genetická a biologická ochrana GMO',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (75,'GIRI','Genetické inženýrství',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (76,'GENMOZ','Geneticky modifikované organismy v zemědělství',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (77,'GENF','Genetika FYTO',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (78,'GKZ','Genetika kvantitativních znaků',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (79,'GESP','Genetika skotu a prasat',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (80,'GEOD2','Geodézie AE II',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (81,'HIPR','Hiporehabilitace',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (82,'HYDRM','Hydraulické mechanismy',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (83,'RHAR','Hydrobiologie a rybářství',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (84,'RHCHE','Hydrochemie',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (85,'CIAM','Chemické instrumentální analytické metody',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (86,'CHE','Chemie',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (87,'CHE-P','Chemie - P',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (88,'CAL-C','Chemie analytická - CV',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (89,'CAL-P','Chemie analytická - P',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (90,'CARS','Chemie anorganická - seminář',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (91,'CAA-TP','Chemie anorganická a analytická - TP - P',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (92,'CAO-C','Chemie anorganická a organická - CV',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (93,'CAO-P','Chemie anorganická a organická - P',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (94,'CFZ','Chemie fyzikální',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (95,'CHOBE','Chemie obecná',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (96,'CHOBES','Chemie obecná - seminář',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (97,'COR','Chemie organická',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (98,'COS','Chemie organická - seminář',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (99,'CHPOS','Chemie potravin speciální',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (100,'CHRYB','Choroby ryb',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (101,'CHDZ','Chov domácích zvířat',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (102,'CHDR','Chov drůbeže',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (103,'CHZ-AE','Chov hospodářských zvířat 1',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (104,'CHKONS','Chov koní - specializace',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (105,'CHKZK','Chov kožešinových zvířat a králíků',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (106,'CHPR','Chov prasat',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (107,'CHSK','Chov skotu',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (108,'CHDR1','Chov vodní drůbeže',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (109,'CHVZZ','Chov volně žijících zvířat',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (110,'RICHT','Ichtyologie obecná',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (111,'IDAS','Informační a datové systémy v zemědělství',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (112,'IZS','Informační zdroje a software',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (113,'INEK1','Informatika',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (114,'JEVO','Jezdectví a vozatajství',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (115,'KARTG','Kartografie',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (116,'KLOP','Klasifikace a ochrana půd',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (117,'KOMOS','Komunální odpady a skládkování',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (118,'KOMOS1','Komunální odpady a skládkování 1',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (119,'KOMVY','Komunitní výživa',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (120,'KCAD','Konstruování v CAD',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (121,'KSK','Konzervace a skladování krmiv',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (122,'OPK','Koroze a ochrana proti korozi',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (123,'KBPT','Koření a byliny v potravinářských technologiích',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (124,'KRSO','Krajina v souvislostech',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (125,'KREKO','Krajinná ekologie',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (126,'KRAUZ','Krajinné a územní plánování',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (127,'KRPO','Krmivářské poradenství',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (128,'KESW','Krmivářský a experimentální software',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (129,'KRM','Krmivářství',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (130,'KRSM','Krmné směsi',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (131,'KZP','Kvalita a zdraví půd',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (132,'KYN','Kynologie',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (133,'LOH2','Legislativa OH II',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (134,'LOGS','Logistika',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (135,'MAN','Management',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (136,'MNGJ','Management jakosti',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (137,'MANOH','Management OH',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (138,'MNGRT','Management rizik technologií OH',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (139,'MNDO','Manažerské dovednosti',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (140,'MT','Matematika',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (141,'MTS','Matematika - seminář',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (142,'METE','Mechanika tekutin',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (143,'MEVPR','Mechanizace výrobních procesů',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (144,'MEZV','Mechanizace živočišné výroby',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (145,'MEPOV','Metodologie potravinářského výzkumu',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (146,'MGZV','Metody genomiky zvířat',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (147,'MIBR','Mikrobiologie MBB',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (148,'MIPR','Mikrobiologie prostředí',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (149,'MLTE','Mlékárenské technologie',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (150,'MBP','Modelování biologických procesů',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (151,'MEOPR','Modelování erozních a odtokových procesů',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (152,'MOB','Molekulární biologie',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (153,'FYVRZ','Molekulární fyziologie živočichů',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (154,'MGEZI','Molekulární genetika živočichů',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (155,'MFYHZ','Morfologie a fyziologie hospodářských zvířat',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (156,'MFK','Morfologie a fyziologie koní',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (157,'MOVOZ2','Motorová vozidla II',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (158,'MYSL','Myslivost',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (159,'NKZ','Nemoci koní a zoohygiena',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (160,'NZEAG','Netradiční zdroje energie v agrosektoru',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (161,'OFPAT','Obecná fytopatologie',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (162,'OHYGP','Obecná hygiena potravin',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (163,'OZOOTR','Obecná zootechnika a reprodukce',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (164,'OZOOT1','Obecná zootechnika 1',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (165,'OTEC','Obchod s technikou',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (166,'OMSTR','Obchodní a marketingové strategie',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (167,'OCEMP','Oceňování majetku a likvidace pojistných událostí',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (168,'OTAKO','Odborný jazyk - angličtina - koně',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (169,'ODSF1','Odborný seminář I',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (170,'ODSF5','Odborný seminář V',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (171,'ODPHO','Odpadové hospodářství',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (172,'OOS','Odrůdy, osivo a sadba',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (173,'OCHPR1','Ochrana přírody a krajiny 1',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (174,'OZP','Ochrana zahradních plodin',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (175,'OCHZP','Ochrana životního prostředí',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (176,'OZA','Okrasné zahradnictví',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (177,'OMA','Operační management',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (178,'OVOVI','Ovocnictví a vinohradnictví',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (179,'PASTS','Pastvinářství v tropech a subtropech',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (180,'PEVR','Pedologie a výživa rostlin',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (181,'PVR-TP','Pěstování a výživa rostlin',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (182,'POTP1','Pěstování okopanin a olejnin',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (183,'PRORS','Pěstování rostlin',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (184,'PRPN','Pěstování rostlin pro nepotravinářské účely',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (185,'PTEP','Pěstování technických a speciálních plodin',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (186,'EKO','Podniková ekonomika',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (187,'MNG','Podnikový management',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (188,'PVZP','Posuzování vlivů na životní prostředí',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (189,'POGI','Potravinářská genomika',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (190,'PTE','Potravinářská technika',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (191,'POIN','Potravinářské inženýrství',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (192,'POTZB','Potravinářské zbožíznalství',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (193,'POZPR','Pozemkové právo',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (194,'PPVD','Právní předpisy v dopravě',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (195,'PRA','Právo',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (196,'PRLTO','Právo a legislativa pro technické obory',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (197,'PRAPO','Právo v podnikání',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (198,'PRZPR','Právo životního prostředí',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (199,'PRAXRD','Praxe diplomová - 8 týdnů RYB',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (200,'PCHZ','Prevence chorob zvířat',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (201,'PZRYB','Produkce a zpracování ryb',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (202,'PSHZ','Produkční systémy hospodářských zvířat',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (203,'PSHZ1','Produkční systémy hospodářských zvířat 1',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (204,'PSPD','Produkční systémy prasat a drůbeže',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (205,'PSPR','Produkční systémy přežvýkavců',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (206,'PSRV2','Produkční systémy v rostlinné výrobě',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (207,'PRGTV','Programování a technické výpočty',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (208,'PRPU','Projektování pozemkových úprav 1',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (209,'PRPRV','Prostředky pro rostlinnou výrobu',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (210,'PST','Provoz stacionární techniky',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (211,'PMOV','Příslušenství motorových vozidel',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (212,'PUDZ1','Půdoznalství FYTO',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (213,'RADO','Radioaktivní odpady',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (214,'RBIM','Radiobiologie a izotopové metody',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (215,'RADEK','Radioekologie',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (216,'REHZ1','Reprodukce hospodářských zvířat 1',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (217,'REUMT','Revitalizace a úprava malých toků',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (218,'RNAT','RNA technologie',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (219,'ROEX','Rostlinné explantáty',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (220,'RLENT','Rostlinolékařská entomologie',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (221,'RUSO','Rurální sociologie',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (222,'RYBUN','Rybníky a účelové nádrže',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (223,'ROS','Řízení a obsluha strojů',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (224,'RLZD','Řízení lidských zdrojů',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (225,'SARE','Sanace a rekultivace',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (226,'SENANP','Senzorická analýza potravin',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (227,'CBSB','Senzory a biosenzory',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (228,'SKSPA','Skladištní škůdci a parazité',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (229,'SPHYP','Speciální hygiena potravin',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (230,'SPMIKR','Speciální mikrobiologie',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (231,'SMOVZ','Speciální motorová vozidla',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (232,'STZPD','Statistické zpracování dat',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (233,'SOH','Stavby pro OH',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (234,'STRT1','Strojírenská technologie',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (235,'SYB','Systematická botanika',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (236,'SYRV','Systémy rostlinné výroby',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (237,'SRZN','Systémy řízení jakosti a zdravotní nezávadnosti',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (238,'SVK','Systémy využití koní',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (239,'SYVR','Systémy výživy rostlin',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (240,'SLR','Šlechtění rostlin',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (241,'SLRSE','Šlechtění rostlin N',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (242,'SLR1','Šlechtění rostlin 1',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (243,'TEINV','Technická infrastruktura venkova',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (244,'TMSAD','Technická měření, sběr a analýza dat',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (245,'TEMY','Technické materiály',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (246,'TEZN','Technické znalectví',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (247,'TEAU','Technický audit',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (248,'TTRV','Technika a technologie pro RV',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (249,'TBET','Technika bioenergetických transformací',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (250,'TKHZ','Technika krmení hospodářských zvířat',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (251,'TKOMS','Technika pro komunální služby',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (252,'TZZEP','Technika pro zpracování zeměděl. produktů',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (253,'TECCE','Technologie cereálií',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (254,'TEDP','Technologie drůbežářského průmyslu',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (255,'TEMA','Technologie masa',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (256,'TESA','Technologie sacharidů',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (257,'TSND','Technologie silniční nákladní dopravy',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (258,'TRZO1','Termické zpracování odpadů 1',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (259,'TRM','Termomechanika',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (260,'TRA','Traktory a automobily',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (261,'TGSK','Transgenoze savců a klonování',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (262,'TREK','Travinné ekosystémy',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (263,'TRIBG','Tribologie a tribotechnika',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (264,'TRVP','Tvorba výnosu polních plodin',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (265,'UDPR','Účetní a daňová propedeutika',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (266,'UOMV','Údržba a opravy motorových vozidel',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (267,'UOS','Údržba a opravy strojů',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (268,'UOSS','Údržba, opravy a servis strojů',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (269,'USPV1','Udržitelná výroba a spotřeba 1',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (270,'UBIF','Úvod do bioinformatiky',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (271,'UEAS','Úvod do ekonomiky agrárního sektoru',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (272,'TVCP','Včelí produkty',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (273,'VSA','Venkovské stavby a architektura',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (274,'VINR','Vinařství',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (275,'VIBA','Virologie a bakteriologie',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (276,'VSZEM','Všeobecné zemědělství',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (277,'VJZP','Výroba a jakost živočišných produktů',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (278,'VVOH','Výroba a využití organických hnojiv',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (279,'VGRO','Vývojová genetika rostlin',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (280,'VKDZ','Výživa a krmení domácích zvířat',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (281,'VKHZ','Výživa a krmení hospodářských zvířat',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (282,'VKHZ2','Výživa a krmení hospodářských zvířat 2',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (283,'VKNZ','Výživa a krmení nepřežvýkavých zvířat',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (284,'RVAKR','Výživa a krmení ryb',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (285,'VYCL','Výživa člověka',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (286,'VYCLDIE','Výživa člověka a dietetika',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (287,'VYZKP','Výživa zvířat a kvalita produkce',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (288,'ZEA','Základy elektroniky a automatizace',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (289,'ZAGE','Základy genomiky',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (290,'ZAGEP','Základy genomiky a proteomiky',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (291,'ZGIS','Základy GIS',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (292,'ZHCHE','Základy hydrochemie',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (293,'ZAKKI','Základy krajinného inženýrství',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (294,'ZPR','Základy projektování',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (295,'ZKPRA','Základy proteomické analýzy',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (296,'ZKRYB','Základy rybníkářství',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (297,'ZKSPR','Základy správního práva',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (298,'ZVETM','Základy veterinární medicíny',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (299,'ZVCL','Základy výživy člověka',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (300,'ZABU','Zařízení budov',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (301,'ZNPZ','Zdravotní nezávadnost potravinových zdrojů',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (302,'ZEL','Zelinářství',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (303,'ZEMI','Zemědělská mikrobiologie',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (304,'ZEMIZO','Zemědělská mikrobiologie ZOO',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (305,'ZPOL','Zemědělská politika',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (306,'ZS','Zemědělské stavby',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (307,'ZHPCZ','Zoohygiena a prevence chorob 2',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (308,'ZOOL','Zoologie',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (309,'ZRP','Zpracování rostlinných produktů',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (310,'ZZEP','Zpracování zemědělských produktů',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (311,'ZZEP1','Zpracování zemědělských produktů 1',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (312,'ZZVP1','Zpracování živočišných produktů 1',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (313,'Z-FIPR','ZS-Final Project',2);
INSERT INTO subject(id,code,name,faculty_id) VALUES (314,'AGD1','Ateliér grafického designu I',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (315,'ANS4','Ateliér nábytkových souborů III',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (316,'ANS5','Atelier nábytkových souborů V',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (317,'BMST','Biomechanika stromu',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (318,'BKZA','Biotechnika krajinné zeleně',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (319,'BOTSP','Botanika speciální',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (320,'VOSN','Dějiny a bydlení',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (321,'DU','Dějiny umění',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (322,'DE3','Dendrologie III',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (323,'DENDL','Dendrologie s ekologií lesních dřevin',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (324,'DSAT','Dendrologie subtropů a tropů',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (325,'DHST','Design, historie, současné trendy',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (326,'EKKR','Ekologie krajiny a geobiocenologie',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (327,'ERSMS','Erasmus',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (328,'EXO','Extenzivní ovocnictví',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (329,'FLZP','Funkce lesa v životním prostředí',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (330,'FVDR','Fyzikální vlastnosti dřeva',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (331,'HINFL','Hospodářská informatika',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (332,'HYST','Hydrotechnické stavby',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (333,'CHZST','Chov hospodářských zvířat v subtropech a tropech',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (334,'IKON','Interiérové konstrukce',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (335,'INK','Interiérové konstrukce',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (336,'IMTD','Inženýrská matematika pro NI',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (337,'KNN3','Konstrukce nábytku III',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (338,'KG-L','Konstruktivní geometrie',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (339,'LDPM','Logistika v dřevozpracujícím průmyslu (modul O, V)',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (340,'MLH','Management',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (341,'MNGN','Management',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (342,'DMU','Manažerské účetnictví',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (343,'NMU','Manažerské účetnictví',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (344,'MKE','Marketing',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (345,'NKTS','Nauka o krajině tropů a subtropů',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (346,'NDK','Navrhování dřevěných konstrukcí',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (347,'OPAEP','Ochrana přírody a environmentální politika',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (348,'OZPN','Ochrana životního prostředí v nábytkovém průmyslu',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (349,'PEDS','Podniková ekonomika',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (350,'PAOS','Posuzování a oceňování stromů',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (351,'PZVP','Povolení zápisu volitelné praxe',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (352,'PNLS','Právní normy v lesním hospodářství',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (353,'PRXDS','Provozní praxe STAV',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (354,'PDKS','Průzkum a dokumentování dřevěných konstrukcí',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (355,'REMF','Řízení a ekonomika malých firem',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (356,'RNSAL','Řízení nábytkářských strojů a linek',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (357,'SVTE','Speciální výrobní technologie',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (358,'SKK','Statistická kontrola kvality',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (359,'STVA','Stavebně truhlářská výroba I',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (360,'SM','Stavební mechanika',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (361,'SRK','Systémy řízení kvality',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (362,'TTP1','Techniky tvorby interiéru I (I)',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (363,'TPVV','Technologické projektování ve výrobě nábytku',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (364,'TCV','Technologie čalounické výroby',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (365,'TTA1','Tepelná technika',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (366,'TTADN','Tepelná technika a akustika v dřevostavbách',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (367,'TVPD','Tvorba projektové dokumentace',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (368,'UST','Úvod do staveb',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (369,'UPARR','Územní plánování a regionální rozvoj',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (370,'VPD','Výroba a provádění dřevostaveb',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (371,'VAM','Výroba aglomerovaných materiálů',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (372,'VMDS','Výroba vrstvených materiálů',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (373,'ZDAG','Základy DPZ a GIS',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (374,'ZOPZ','Základy obhospodařování přírodních zdrojů subtropů a tropů',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (375,'ZOL','Základy ochrany lesa',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (376,'ZAKA','Základy ZaKa I',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (377,'ZLS','Zpřístupňování lesa',3);
INSERT INTO subject(id,code,name,faculty_id) VALUES (378,'AMA','Aplikovaná matematika I',4);
INSERT INTO subject(id,code,name,faculty_id) VALUES (379,'AMA2','Aplikovaná matematika II',4);
INSERT INTO subject(id,code,name,faculty_id) VALUES (380,'ATE','Automatizační technika',4);
INSERT INTO subject(id,code,name,faculty_id) VALUES (384,'BSA','Bakalářský seminář IS/ICT',4);
INSERT INTO subject(id,code,name,faculty_id) VALUES (385,'DPR','Daňové teorie',4);
INSERT INTO subject(id,code,name,faculty_id) VALUES (386,'DISI','Diplomní seminář IS/ICT',4);
INSERT INTO subject(id,code,name,faculty_id) VALUES (387,'DISK','Diplomní seminář Kybernetika',4);
INSERT INTO subject(id,code,name,faculty_id) VALUES (391,'EMM','Ekonomicko matematické metody',4);
INSERT INTO subject(id,code,name,faculty_id) VALUES (392,'NIT','E-technologie',4);
INSERT INTO subject(id,code,name,faculty_id) VALUES (393,'GIS','Geografické informační systémy',4);
INSERT INTO subject(id,code,name,faculty_id) VALUES (394,'HPO1','Hospodářská politika I',4);
INSERT INTO subject(id,code,name,faculty_id) VALUES (395,'IT','Informační systémy a technologie',4);
INSERT INTO subject(id,code,name,faculty_id) VALUES (396,'IE2','Informatika pro ekonomy II',4);
INSERT INTO subject(id,code,name,faculty_id) VALUES (397,'IIS','Integrované informační systémy',4);
INSERT INTO subject(id,code,name,faculty_id) VALUES (398,'IKK','Interkulturní kompetence',4);
INSERT INTO subject(id,code,name,faculty_id) VALUES (399,'IS','IS podniku',4);
INSERT INTO subject(id,code,name,faculty_id) VALUES (400,'ICTE','IS/ICT v environmentu',4);
INSERT INTO subject(id,code,name,faculty_id) VALUES (401,'IIZP','IS/ICT v zemědělství a potravinářství',4);
INSERT INTO subject(id,code,name,faculty_id) VALUES (402,'JA','Java aplikace',4);
INSERT INTO subject(id,code,name,faculty_id) VALUES (403,'KAS','Komprimace dat a kryptologie',4);
INSERT INTO subject(id,code,name,faculty_id) VALUES (404,'KAR','Kvantitativní analýza rizika',4);
INSERT INTO subject(id,code,name,faculty_id) VALUES (405,'LVR','Laboratoř virtuální reality',4);
INSERT INTO subject(id,code,name,faculty_id) VALUES (406,'LGA','Logistika',4);
INSERT INTO subject(id,code,name,faculty_id) VALUES (407,'ME','Manažerské dovednosti',4);
INSERT INTO subject(id,code,name,faculty_id) VALUES (408,'MR','Manažerské rozhodování',4);
INSERT INTO subject(id,code,name,faculty_id) VALUES (409,'MUC','Manažerské účetnictví',4);
INSERT INTO subject(id,code,name,faculty_id) VALUES (410,'MKV','Marketingová komunikace',4);
INSERT INTO subject(id,code,name,faculty_id) VALUES (411,'MS1','Měřicí systémy I',4);
INSERT INTO subject(id,code,name,faculty_id) VALUES (412,'MFM','Mezinárodní marketing',4);
INSERT INTO subject(id,code,name,faculty_id) VALUES (413,'MMFZ','Mezinárodní měnové a finanční vztahy',4);
INSERT INTO subject(id,code,name,faculty_id) VALUES (414,'MOP','Mezinárodní obchodní právo',4);
INSERT INTO subject(id,code,name,faculty_id) VALUES (415,'OCP','Oceňování podniku',4);
INSERT INTO subject(id,code,name,faculty_id) VALUES (416,'PRX','Odborná praxe',4);
INSERT INTO subject(id,code,name,faculty_id) VALUES (417,'OM','Optimalizační metody',4);
INSERT INTO subject(id,code,name,faculty_id) VALUES (418,'PAP','Počítačové aplikace',4);
INSERT INTO subject(id,code,name,faculty_id) VALUES (419,'PS','Počítačové sítě I',4);
INSERT INTO subject(id,code,name,faculty_id) VALUES (420,'PS2','Počítačové sítě II',4);
INSERT INTO subject(id,code,name,faculty_id) VALUES (421,'PCR','Podnikání v cestovním ruchu',4);
INSERT INTO subject(id,code,name,faculty_id) VALUES (422,'AVT','Praxe vývojových technik',4);
INSERT INTO subject(id,code,name,faculty_id) VALUES (423,'AVTK','Praxe vývojových technik Kybernetika',4);
INSERT INTO subject(id,code,name,faculty_id) VALUES (424,'PTN','Programovací techniky',4);
INSERT INTO subject(id,code,name,faculty_id) VALUES (425,'PR','Public relations',4);
INSERT INTO subject(id,code,name,faculty_id) VALUES (426,'REK','Reformy české a světové ekonomiky',4);
INSERT INTO subject(id,code,name,faculty_id) VALUES (427,'RFT','Regulace a dohled finančních trhů',4);
INSERT INTO subject(id,code,name,faculty_id) VALUES (428,'PRX2','Řízená odborná praxe',4);
INSERT INTO subject(id,code,name,faculty_id) VALUES (429,'SKK','Seminář komerční komunikace',4);
INSERT INTO subject(id,code,name,faculty_id) VALUES (430,'SOC','Sociologie a sociální psychologie',4);
INSERT INTO subject(id,code,name,faculty_id) VALUES (431,'SRA','Správní řízení a jeho aplikace ve veřejné správě',4);
INSERT INTO subject(id,code,name,faculty_id) VALUES (436,'SP','Systém sociálního zabezpečení',4);
INSERT INTO subject(id,code,name,faculty_id) VALUES (437,'SI','Systémové inženýrství',4);
INSERT INTO subject(id,code,name,faculty_id) VALUES (438,'TI','Teoretická informatika',4);
INSERT INTO subject(id,code,name,faculty_id) VALUES (439,'TEI','Teorie měnové integrace',4);
INSERT INTO subject(id,code,name,faculty_id) VALUES (440,'TPJ','Teorie programovacích jazyků',4);
INSERT INTO subject(id,code,name,faculty_id) VALUES (441,'UCR','Účetnictví a daně v CR',4);
INSERT INTO subject(id,code,name,faculty_id) VALUES (442,'WA','Webové aplikace',4);
INSERT INTO subject(id,code,name,faculty_id) VALUES (443,'WD','Webový design',4);
INSERT INTO subject(id,code,name,faculty_id) VALUES (444,'ZDM','Zpracování dat pro manažery',4);
INSERT INTO subject(id,code,name,faculty_id) VALUES (445,'ARV','Agrotechnika révy vinné',5);
INSERT INTO subject(id,code,name,faculty_id) VALUES (446,'APFT','Alternativní produkce v zahradnictví FT',5);
INSERT INTO subject(id,code,name,faculty_id) VALUES (447,'AMRV','Ampelografie révy vinné',5);
INSERT INTO subject(id,code,name,faculty_id) VALUES (448,'APBO','Aplikovaná botanika',5);
INSERT INTO subject(id,code,name,faculty_id) VALUES (449,'ARR1','Aranžování rostlin 1',5);
INSERT INTO subject(id,code,name,faculty_id) VALUES (450,'ATB2','Ateliér biotechniky II',5);
INSERT INTO subject(id,code,name,faculty_id) VALUES (451,'ATP','Ateliér projektování',5);
INSERT INTO subject(id,code,name,faculty_id) VALUES (452,'ANZ','Ateliéry navrhování ZaKA',5);
INSERT INTO subject(id,code,name,faculty_id) VALUES (454,'BO1','Botanika I',5);
INSERT INTO subject(id,code,name,faculty_id) VALUES (455,'DU4','Dějiny umění IV',5);
INSERT INTO subject(id,code,name,faculty_id) VALUES (456,'DE2','Dendrologie II',5);
INSERT INTO subject(id,code,name,faculty_id) VALUES (457,'DE3','Dendrologie III',5);
INSERT INTO subject(id,code,name,faculty_id) VALUES (458,'DEFL','Dendrologie pro floristy',5);
INSERT INTO subject(id,code,name,faculty_id) VALUES (460,'EST','Estetika',5);
INSERT INTO subject(id,code,name,faculty_id) VALUES (461,'FLA1','Floristický ateliér 1',5);
INSERT INTO subject(id,code,name,faculty_id) VALUES (462,'FLA3','Floristický ateliér 3',5);
INSERT INTO subject(id,code,name,faculty_id) VALUES (463,'FLPR','Floristický provoz',5);
INSERT INTO subject(id,code,name,faculty_id) VALUES (464,'FCE','Fytocenologie',5);
INSERT INTO subject(id,code,name,faculty_id) VALUES (465,'FRO','Fyziologie rostlin',5);
INSERT INTO subject(id,code,name,faculty_id) VALUES (466,'CHA','Chemie anorganická a analytická',5);
INSERT INTO subject(id,code,name,faculty_id) VALUES (467,'CHAS','Chemie anorganická a analytická - seminář',5);
INSERT INTO subject(id,code,name,faculty_id) VALUES (468,'IK2','Interiérové květinářství II',5);
INSERT INTO subject(id,code,name,faculty_id) VALUES (469,'IK','Interpretace krajiny',5);
INSERT INTO subject(id,code,name,faculty_id) VALUES (470,'KP1Z','Krajinné plánování I pro ZKA',5);
INSERT INTO subject(id,code,name,faculty_id) VALUES (471,'KZ1','Květinářství pro ZAKA I',5);
INSERT INTO subject(id,code,name,faculty_id) VALUES (472,'MAR','Marketing',5);
INSERT INTO subject(id,code,name,faculty_id) VALUES (473,'MKII','Materiály a konstrukce II',5);
INSERT INTO subject(id,code,name,faculty_id) VALUES (474,'PRXV','Odborná praxe - VaV',5);
INSERT INTO subject(id,code,name,faculty_id) VALUES (475,'OOR','Ochrana okrasných rostlin',5);
INSERT INTO subject(id,code,name,faculty_id) VALUES (476,'OTS','Ovocnictví tropů a subtropů',5);
INSERT INTO subject(id,code,name,faculty_id) VALUES (477,'PED','Pedologie',5);
INSERT INTO subject(id,code,name,faculty_id) VALUES (478,'POEM','Podniková ekonomika (MZKU)',5);
INSERT INTO subject(id,code,name,faculty_id) VALUES (479,'PR2','Použití rostlin II',5);
INSERT INTO subject(id,code,name,faculty_id) VALUES (480,'POZE','Použití zelenin',5);
INSERT INTO subject(id,code,name,faculty_id) VALUES (481,'P2','Praktika II pro ZKR',5);
INSERT INTO subject(id,code,name,faculty_id) VALUES (482,'PRX','Praxe - 3 týdny / 120 hodin',5);
INSERT INTO subject(id,code,name,faculty_id) VALUES (483,'PRA18LS','Praxe v areálu LS 2017/2018 - 2 dny / 16 hodin',5);
INSERT INTO subject(id,code,name,faculty_id) VALUES (484,'PRA19LS','Praxe v areálu LS 2018/2019 - 2 dny / 16 hodin',5);
INSERT INTO subject(id,code,name,faculty_id) VALUES (485,'PRA20LS','Praxe v areálu LS 2019/2020 - 2 dny / 16 hodin',5);
INSERT INTO subject(id,code,name,faculty_id) VALUES (486,'PRA21LS','Praxe v areálu LS 2020/2021 - 2 dny / 16 hodin',5);
INSERT INTO subject(id,code,name,faculty_id) VALUES (487,'PRA17ZS','Praxe v areálu ZS 2017/2018 - 2 dny / 16 hodin',5);
INSERT INTO subject(id,code,name,faculty_id) VALUES (488,'PRA18ZS','Praxe v areálu ZS 2018/2019 - 2 dny / 16 hodin',5);
INSERT INTO subject(id,code,name,faculty_id) VALUES (489,'PRA19ZS','Praxe v areálu ZS 2019/2020 - 2 dny / 16 hodin',5);
INSERT INTO subject(id,code,name,faculty_id) VALUES (490,'PRA20ZS','Praxe v areálu ZS 2020/2021 - 2 dny / 16 hodin',5);
INSERT INTO subject(id,code,name,faculty_id) VALUES (491,'PRA21ZS','Praxe v areálu ZS 2021/2022 - 2 dny / 16 hodin',5);
INSERT INTO subject(id,code,name,faculty_id) VALUES (492,'PSOS','Psychologie v obchodním styku',5);
INSERT INTO subject(id,code,name,faculty_id) VALUES (493,'SKV','Skleníková výroba',5);
INSERT INTO subject(id,code,name,faculty_id) VALUES (496,'URK','Úchova řezaných květin',5);
INSERT INTO subject(id,code,name,faculty_id) VALUES (497,'U3V','Univerzita 3. věku',5);
INSERT INTO subject(id,code,name,faculty_id) VALUES (498,'URB','Urbanismus',5);
INSERT INTO subject(id,code,name,faculty_id) VALUES (499,'URB2','Urbanismus II',5);
INSERT INTO subject(id,code,name,faculty_id) VALUES (500,'UZPZ','Územní plánování pro ZKA',5);
INSERT INTO subject(id,code,name,faculty_id) VALUES (501,'VYT','Výpočetní technika',5);
INSERT INTO subject(id,code,name,faculty_id) VALUES (502,'VT4','Výtvarná tvorba IV',5);
INSERT INTO subject(id,code,name,faculty_id) VALUES (503,'VLVA','Vývoj Lednicko-valtického areálu',5);
INSERT INTO subject(id,code,name,faculty_id) VALUES (504,'WS1','Workshop I',5);
INSERT INTO subject(id,code,name,faculty_id) VALUES (505,'ZA2','Zahradně architektonická tvorba II',5);
INSERT INTO subject(id,code,name,faculty_id) VALUES (506,'ZVY','Zahradnické výstavnictví',5);
INSERT INTO subject(id,code,name,faculty_id) VALUES (507,'ZVI','Základy vinařství',5);
INSERT INTO subject(id,code,name,faculty_id) VALUES (508,'RRAS','Aplikovaná statistika',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (510,'RRBS','Bakalářský seminář',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (511,'DEZD','Demogeografie zdraví',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (512,'RRDELK','Demografie lidského kapitálu',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (514,'DS','Diplomový seminář',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (515,'EKPR','Ekonomické procesy v rozvojových zemích',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (516,'EKVS','Ekonomie veřejného sektoru',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (517,'RRERZP','Ekonomika a řízení životního prostředí a přírodních zdrojů',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (518,'EZELE','Ekonomika zemědělství a lesnictví',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (519,'EKSL','Ekosystémové služby',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (520,'EPMP','Environmentální politika v mezinárodním prostředí',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (521,'ENPE','Environmentální problémy Evropy',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (522,'EPRS','Environmentální problémy rozvojového světa',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (523,'RREUGA','Evropská unie jako globální aktér',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (524,'FIRS','Financování rozvojové spolupráce',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (525,'GESE','Geografie střední Evropy',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (526,'RRGE','Globální environmentalistika',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (527,'HVEU','Historický a institucionální vývoj EU',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (528,'IPS','Interkulturní psychologie',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (529,'RRIAR','Investiční atraktivnost regionů: teorie a praxe',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (530,'KD','Kulturní dědictví',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (531,'RRMAE','Makroekonomie',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (532,'MALZ','Management lidských zdrojů',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (533,'MEK','Manažerská ekonomika',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (534,'RRMAT','Matematika',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (535,'RRMO','Mezinárodní obchod',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (536,'MEVZ','Mezinárodní vztahy a současné bezpečnostní výzvy',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (537,'RRMIE','Mikroekonomie',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (538,'NARP','Nástroje pro řízení projektů',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (539,'RRODA','Obecná demografie',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (543,'PEZP','Péče o životní prostředí',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (544,'RRPNF','Podnikové finance',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (545,'POMY','Politické myšlení',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (546,'PVRS','Politické výzvy rozvojového světa',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (547,'PROM','Projektový management',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (548,'RRPZS','Příprava zahraniční stáže',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (549,'RKPO','Regionální a kohezní politika',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (550,'REDES','Regionální demografie a sídla',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (551,'RRREK','Regionální ekonomika',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (552,'RRRSO','Regionální sociologie',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (553,'RRRVZP','Rozvoj venkova a zemědělská politika',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (554,'RRRZR','Rozvoj zdravého regionu',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (555,'RRRA','Rozvojová antropologie',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (556,'RPC','Rozvojové problémy Číny',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (557,'RUST','Rurální studia',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (558,'SPSS','Sociální problémy současné společnosti',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (559,'RRSPS','Sociální psychologie',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (560,'RRSOC','Sociologie',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (561,'SNO','Správní nástroje ochrany životního prostředí',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (562,'STAN','Statistické analýzy',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (565,'SPRO','Strategické plánování a rozhodování',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (566,'SLES','Světové lesnictví',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (567,'RRTRR','Teorie regionálního rozvoje',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (568,'RRIDS','Úvod do rozvojových studií',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (569,'RRVEF','Veřejné finance',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (570,'RRVPZRS','Využívání přírodních zdrojů',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (571,'VLRR','Význam lesů v regionálním rozvoji',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (572,'ZAPS','Základy akademického psaní',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (573,'RRZE','Základy environmentalistiky',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (574,'RRGISR','Základy GIS',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (575,'ZMAR','Základy marketingu',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (576,'ZMET','Základy metodologie',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (577,'RRZPR','Základy projektového řízení',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (578,'RRZIP','Živnostenské podnikání',6);
INSERT INTO subject(id,code,name,faculty_id) VALUES (579,'APST','Aplikovaná statistika',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (583,'BOZPI','Bezpečnost a ochrana zdraví při práci',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (584,'BOOV','Bezpečnost a ochrana zdraví žáků v praktickém vyučování a odborném výcviku',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (585,'BEPA','Bezpečnost práce',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (586,'BINI','Bionika',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (587,'DSOV','Dějiny a současnost učňovského a odborného školství',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (588,'DVOP','Didaktika praktického vyučování',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (589,'D2PA','Didaktika praktického vyučování II',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (590,'DTOV','Digitální technologie ve vzdělávání',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (592,'DPSI','Diplomový seminář',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (593,'ERPT','Ekonomika a řízení pojišťovnictví',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (594,'EIAP','Ekonomika vzdělávacích institucí',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (595,'EVOP','Enviromentální výchova v odborném vzdělávání',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (596,'EVPA','Environmentální výchova',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (597,'FMEI','Facility management',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (598,'HVOV','Hlasová výchova a komunikace',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (599,'ICOP','Informační a komunikační technologie',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (600,'KDPA','Komunikační dovednosti',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (601,'KCPT','Kriminalita v pojišťovnictví',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (602,'MMOP','Management a marketing školy',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (603,'MMAP','Marketing a management ve vzdělávání',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (604,'MSPA','Marketing školy',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (605,'MEZT','Mechanika tekutin',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (606,'MVOP','Metodika výuky',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (607,'NSEI','Normy a standardy',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (608,'ODOP','Obecná didaktika',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (609,'ODAP','Obecná pedagogika',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (610,'OPOV','Obecná pedagogika',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (611,'OSOV','Obecná psychologie',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (612,'OIOV','Oborové instrumentárium',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (613,'OVOV','Odborná orientace v oboru',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (614,'OEPA','Odborné exkurze a inovace',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (615,'PDPA','Pedagogická diagnostika',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (616,'PPPA','Pedagogická psychologie',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (617,'AJSPV','Podpůrný kurz angličtiny pro studenty s poruchami učení',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (618,'PJPA','Prevence sociálně patologických jevů',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (619,'ETPA','Profesní etika',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (620,'SWZT','Projektování v Solid Works',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (621,'PMEI','Projektový management',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (622,'PSOP','Psychologie pro učitele',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (623,'PFAP','Řízení projektů a fundraising',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (624,'RRPI','Řízení rizik projektů',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (625,'RTPI','Řízení technologických procesů',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (626,'SBOP','Seminář k bakalářské práci',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (627,'B2PA','Seminář k bakalářské práci II',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (628,'PJOP','Sociální patologie a prevence',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (629,'SOOP','Sociální pedagogika',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (630,'OSPA','Sociální psychologie',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (631,'SGOP','Speciální pedagogika',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (632,'SPPA','Speciální pedagogika',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (633,'STME','Startup MENDELU',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (635,'STVT','Stavby',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (636,'S2EI','Stavby 2',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (637,'SVPA','Svět práce',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (638,'CVAP','Systémy celoživotního vzdělávání',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (639,'SMPA','Školský management',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (640,'TZ1T','Technické znalectví I',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (641,'TZ2T','Technické znalectví II',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (642,'TAEI','Technický audit',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (643,'TPRT','Technický projekt',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (644,'TKST','Technika pro komunální služby',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (645,'TEZT','Termomechanika',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (646,'TPPA','Tvorba školního vzdělávacího programu',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (647,'UPOP','Úvod do individuální řízené pedagogické praxe',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (648,'UPPA','Úvod do individuální řízené pedagogické praxe',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (649,'TVOV','Vademecum terciárního vzdělávání',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (650,'VMEI','Vozidlové motory',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (651,'VROP','Výchovné poradenství',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (652,'ISEI','Využití informačních systémů v expertní činnosti',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (653,'VDOP','Vzdělávání dospělých',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (654,'ZMVT','Zkoušení motorových vozidel',7);
INSERT INTO subject(id,code,name,faculty_id) VALUES (655,'ZNMI','Znalecké minimum',7);